server:
  port: 5555

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: core-service
          uri: http://core-service:9090/
          predicates:
            - Path=/core/**
          filters:
            - StripPrefix=1
            - PrefixPath=/
