server:
  port: 5555

spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:8190"
            allowedMethods:
              - GET
              - POST
            allowedHeaders: "*"
      routes:
        - id: core-service
          uri: http://core-service:9090/
          predicates:
            - Path=/core/**
          filters:
            - StripPrefix=1
            - PrefixPath=/
        - id: front-service
          uri: http://front-service:8190
          predicates:
            - Path=/
          filters:
            - StripPrefix=1
            - PrefixPath=/
logging:
  level:
    root: DEBUG
