server:
  port: 9090

spring:

  datasource:
    url: jdbc:postgresql://localhost:5435/postgres
    hikari:
      schema: test_schema
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    default-schema: ${spring.datasource.hikari.schema}
